language: ruby
rvm:
- 2.2.1
before_install: gem install bundler -v 1.10.6
env:
  global:
    secure: db97gVRKY171UjMmh+9EKOlwNrewe1UxvWV9LVMlsvQknf5zowCtqWhQhPpeWiNFMsBr/Jdow20J7nKd922zCkO3Hm5GYfAn7H23Oayxyc1VVHOTU3OcvGy8IvbQTsd8mKpvGfDsXvX84ni+CQ8z0DQ15acYUqXgb1oXlL67uwGA0bpk0cm5ID8OsfEuMs0TEijWkwwH30wZGBhS6ud8lEdXoy9llQy61xZNQx+F/n6iz/HOkqYzEL1DhNzpwuAA+E8GqComuQ83xclfOthUnLW7adXTBziYxpXcbYvZZkZrXFi38ogKdVvmYLw4TRWga55rfpUbCoCZrVSl+bgtnFhmsJpJ+TITXM2hxINSIwcD681oUwYOyE45BsiIuevtSIgZvwecpb74sJXkrmNdoJvXbKmwR3a66mQkb74hk6fe8i9XPZYlS+qS8pHSFOHw/lWQX4ZKD2lvSxGGTIYaqWdX+ECfz6PNO9HqUWoOr80mjYIWxn43pPdlLaCA27nLnxD+G4F32zcpfFpXBGUJhcbYzjf1qVGQVw/Gkbmr6OWBgd8j3NYCxedU/UlE6+centuwQ+Mwv3xQzP1Xrl7KoOqVEI0Q5QB8ixrM14jN7Ltrv26Yvd89B0y83/HmDKVVK1zkMZjLM2fI1z3BrV1Glxu7nBF63cAXHkt9B25TpU8=
