language: ruby
rvm:
- 2.2.1
before_install: gem install bundler -v 1.10.6
env:
  global:
  - secure: ArV6/JVY1iQbAEBN9P5QRMaikbwmnoJyAmrkRPVCClMLFfAPpT8vddqh7AwjriVp+ZZSFUnuVXC/aWdXx9AXkvytS2BuyZDYpY9s0OcNR6Sl+6YZffaoALP710gu9GIXvbNmqpYL5fYK5/r0lL4stHDlWCNcaTV/P5lIoc0FoUhpPsGVIVobylVn4ezyrOp45BK8OaElelmt+/CDJgpshvN5q5bJvHu4osn8owc9WcM5lNJdwvoIhQpuiDqyC9i4DbG9nmAyBwxbfkc9uY3mNSzqBX7Zw/6LEV2KSBDwQ1zsVgwmpkkrXe6uzPSNoRqh0uw2lwW3Vv0qU33wcyQSnDdHpR+e26W4lBNcE5JP8tNW2A7eXtCqqpwzYGiiGddMyAag2rzd/rpPhDb1NgBAYCHB61A5lOjIV1yk7BF7eHGJY5FmJcpwnL3DrF2pGvtlkYor7tS6OV87s8namhId1pqEcU9xn7HEToMNwWOdZ1k3sKxiPSNLD749J3Sh8CCf4LTkVaOe2oLPQ46VehfLccm5wK+mNL1+gFlKSGdFetUFJcA1OJizcZfpHQQM1cCw3KUWpFOlT8Y5EuFaLOfTy8+oTvDg+Y6ebPGrWHbuDZEV/Nk0xldzdATH6ba8mjFmeHPJhpnLxCWF5OwEpGGLqYLObmr6HubCuDM3tR5KNEQ=
addons:
    code_climate:
        repo_token: 3e08785b604c10db0658018324476216e7bc68e9c6f854e1634430b85fda94e1